from handlers.stop_fsm import register_stop_fsm_handler
from handlers.start_command import register_start_command_handlers
from handlers.client.add_new_channel import register_handlers_add_new_channel
from handlers.client.delete_channel import register_handlers_delete_channel
from handlers.client.create_individual_post import register_handlers_create_individual_post
from handlers.client.create_donor_posts import register_handlers_donor_posts
from handlers.client.cancel_posts import register_handlers_cancel_posts
from handlers.client.cancel_donor_posts import register_handlers_cancel_posts_donor

register_stop_fsm_handler()
register_start_command_handlers()
register_handlers_add_new_channel()
register_handlers_delete_channel()
register_handlers_create_individual_post()
register_handlers_cancel_posts()
register_handlers_cancel_posts_donor()
register_handlers_donor_posts()
